core/urls.py
from django.urls import path
from . import views

urlpatterns = [
path('', views.index, name='index' ),
path('settings/', views.settings, name='settings'),
path('upload-post/', views.uploadPost, name="upload"),   
path('like-post/<int:id>', views.likePost, name="like"),   
path('follow-user/<id>', views.followUser, name="follow"),   
path('<str:username>/', views.profile, name="profile"),   
path('search-user', views.searchUser, name="search"),   
]

instaclone/urls.py
import django
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.urls')),
    path('', include('authentication.urls')),
    
    path("__debug__/", include("debug_toolbar.urls")),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/models.py
from email.policy import default
from os import name
from unittest.util import _MAX_LENGTH
from django.db import models
from django.contrib.auth.models import User

class Profile(models.Model):
    bio = models.TextField()
    location = models.CharField(max_length=255)
    profile_img = models.ImageField(upload_to='profilePics', default='profilePics/download.png')
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    
    def __str__(self):
        return self.user.username
    
    
    
class Posts(models.Model):
    img = models.ImageField(upload_to='posts')
    caption = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    likesCount = models.IntegerField(default=0)
    def __str__(self):
        return self.user.username
    
    
class Likes(models.Model):
    likedPost = models.ForeignKey(Posts, on_delete=models.CASCADE)
    likedUser = models.ForeignKey(User, on_delete=models.CASCADE)
    
    
    def __str__(self):
        return self.likedUser.username
    
    
    
class Followers(models.Model):
    follower = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='follower')
    following = models.ForeignKey(Profile, on_delete=models.CASCADE, related_name='following')
    
    def __str__(self):
        return ("Follower: " + self.follower.user.username + " " +"Following: " + self.following.user.username)
    
    

templates/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="favicon.png" rel="icon" type="image/png">
    <title>Home</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'assets/css/icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/uikit.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/tailwind.css' %}">
</head>

<body>

            <header>
                <div class="header_inner">
                    <div class="left-side">
                        <!-- Logo -->
                        <div id="logo" class=" uk-hidden@s">
                            <a href="home.html">
                                <b><h1 style="text-transform: uppercase;">Social Book</h1></b>
                            </a>
                        </div>

                        <!--<div class="triger" uk-toggle="target: #wrapper ; cls: sidebar-active">
                            <i class="uil-bars"></i>
                        </div>-->
<form action="{% url "search" %}" method="post">
{% csrf_token %}
    <div class="header_search">
        <input type="text" placeholder="Search for username.." name='search-user'>
        <div class="icon-search">
            <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24"
            stroke="currentColor">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2"
            d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
        </svg>
    </div>
</div>
</form>

                    </div>
                    <div class="right-side lg:pr-4">
                         <!-- upload -->
                        <a href="#"
                            class="bg-pink-500 flex font-bold hidden hover:bg-pink-600 hover:text-white inline-block items-center lg:block max-h-10 mr-4 px-4 py-2 rounded shado text-white">
                            <ion-icon name="add-circle" class="-mb-1
                             mr-1 opacity-90 text-xl uilus-circle"></ion-icon> Upload Pics / Videos
                        </a>
                         <!-- upload dropdown box -->
                        <div uk-dropdown="pos: top-right;mode:click ; animation: uk-animation-slide-bottom-small" class="header_dropdown">
    
                            <!-- notivication header -->
                            <div class="px-4 py-3 -mx-5 -mt-4 mb-5 border-b">
                                <h4>Upload Pic</h4>
                            </div>
    
                            <!-- notification contents -->
                            <div class="flex justify-center flex-center text-center">
    
                                <div class="flex flex-col choose-upload text-center">
                                   
                                    <div class="bg-gray-100 border-2 border-dashed flex flex-col h-24 items-center justify-center relative w-full rounded-lg  ">
                                        <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" class="w-12">
                                            <path d="M5.5 13a3.5 3.5 0 01-.369-6.98 4 4 0 117.753-1.977A4.5 4.5 0 1113.5 13H11V9.413l1.293 1.293a1 1 0 001.414-1.414l-3-3a1 1 0 00-1.414 0l-3 3a1 1 0 001.414 1.414L9 9.414V13H5.5z" />
                                            <path d="M9 13h2v5a1 1 0 11-2 0v-5z" />
                                        </svg>
                                    </div>

                                    <p class="my-3 leading-6"> Upload pic.<br> please upload here ..
                                    </p>
                                    <form action="{% url "upload" %}" method="POST" enctype="multipart/form-data">
                                        {% csrf_token %}
                                    <input type="file" name="postImage">
                                    <input type="text" placeholder="caption" name="postCaption" style="margin:10px 0">
                                    <div uk-form-custom>
                                        <input class="button soft-warning small" type="submit"> 
                                    </div>
                                </form>
                                   
                                </div>
    
                                
    
                            </div>
                            
                        </div>
                        
                         

                        <!-- profile -->

                        <a href="#">
                            <img src="{{profile.profile_img.url}}" class="header-avatar" alt="">
                        </a>
                        <div uk-drop="mode: click;offset:9" class="header_dropdown profile_dropdown border-t">
                            <ul>
                                <li><a href={% url "settings" %}> Account setting </a> </li>
                                <li><a href="{% url "logout" %}"> Log Out</a></li>
                            </ul>
                        </div>

                    </div>
                </div>
            </header>

            <div class="container m-auto">

                <!--<h1 class="lg:text-2xl text-lg font-extrabold leading-none text-gray-900 tracking-tight mb-5"> Feed </h1>--->

                <div class="lg:flex justify-center lg:space-x-10 lg:space-y-0 space-y-5">

                    <!-- left sidebar-->
                    <div class="space-y-5 flex-shrink-0 lg:w-7/12">


                            {% for post in posts %}
                        <!-- post 1-->
                        <div class="bg-white shadow rounded-md  -mx-2 lg:mx-0">
    
                            <!-- post header-->
                            <div class="flex justify-between items-center px-4 py-3">
                                <div class="flex flex-1 items-center space-x-4">
                                    <a href="/{{post.user.username}} ">
                                        <div class="bg-gradient-to-tr from-yellow-600 to-pink-600 p-0.5 rounded-full">  
                                            <img src=" {{post.user.profile.profile_img.url}} " class="bg-gray-200 border border-white rounded-full w-8 h-8">
                                        </div>
                                    </a>
                                    <span class="block capitalize font-semibold "> {{post.user.username}} </span>
                                </div>
                              <div>
                                <a href="#"> <i class="icon-feather-more-horizontal text-2xl hover:bg-gray-200 rounded-full p-2 transition -mr-1 "></i> </a>
                                <div class="bg-white w-56 shadow-md mx-auto p-2 mt-12 rounded-md text-gray-500 hidden text-base border border-gray-100  " uk-drop="mode: hover;pos: top-right">
                              
                                    <ul class="space-y-1">

                                      <li> 
                                          <a href="#" class="flex items-center px-3 py-2 text-red-500 hover:bg-red-100 hover:text-red-500 rounded-md ">
                                           <i class="uil-trash-alt mr-1"></i>  Delete
                                          </a> 
                                      </li>
                                    </ul>
                                
                                </div>
                              </div>
                            </div>
    
                            <div uk-lightbox>
                                <a href="{% static 'assets/images/post/img4.jpg' %}">  
                                    <img src="{{post.img.url}}" alt="" style="width:100%;height:100%;object-fit:cover">
                                </a>
                            </div>
                            
    
                            <div class="py-3 px-4 space-y-3"> 
                               
                                <div class="flex space-x-4 lg:font-bold">
                                    <a href="like-post/{{post.id}}" class="flex items-center space-x-2">
                                        <div class="p-2 rounded-full text-black">
                                            <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" width="25" height="25" class="">
                                                <path d="M2 10.5a1.5 1.5 0 113 0v6a1.5 1.5 0 01-3 0v-6zM6 10.333v5.43a2 2 0 001.106 1.79l.05.025A4 4 0 008.943 18h5.416a2 2 0 001.962-1.608l1.2-6A2 2 0 0015.56 8H12V4a2 2 0 00-2-2 1 1 0 00-1 1v.667a4 4 0 01-.8 2.4L6.8 7.933a4 4 0 00-.8 2.4z" />
                                            </svg>
                                        </div>
                                        
                                    </a>
                                    <a href="" class="flex items-center space-x-2">
                                        <p>{{post.likesCount}} Likes</p>
                                        
                                    </a>
                                    <a href="#" class="flex items-center space-x-2 flex-1 justify-end">
                                        <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" width="25" height="25" preserveAspectRatio="xMidYMid meet" viewBox="0 0 16 16"><g fill="currentColor"><path d="M8.5 1.5A1.5 1.5 0 0 1 10 0h4a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V2a2 2 0 0 1 2-2h6c-.314.418-.5.937-.5 1.5v6h-2a.5.5 0 0 0-.354.854l2.5 2.5a.5.5 0 0 0 .708 0l2.5-2.5A.5.5 0 0 0 10.5 7.5h-2v-6z"/></g></svg>
                                        
                                    </a>
                                </div>
                                

                                

    
                            </div>
    
                        </div>
                        {% endfor %}
    

                        <!-- Load more-->
                        <div class="flex justify-center mt-6" id="toggle" hidden>
                            <a href="#"
                                class="bg-white  font-semibold my-3 px-6 py-2 rounded-full shadow-md  ">
                                Load more ..</a>
                        </div>


                    </div>

                    <!-- right sidebar-->
                     <div class="lg:w-5/12">

                        <div class="bg-white  shadow-md rounded-md overflow-hidden">

                            <div class="bg-gray-50  border-b border-gray-100 flex items-baseline justify-between py-4 px-6 ">
                                <h2 class="font-semibold text-lg">Users You Can Follow</h2>
                                <a href="#"> Refresh</a>
                            </div>
                           
                            <div class="divide-gray-300 divide-gray-50 divide-opacity-50 divide-y px-4 ">
                                {% for profile in all_profiles %}
                                <div class="flex items-center justify-between py-3">
                                    <div class="flex flex-1 items-center space-x-4">
                                        <a href="profile.html">
                                            <img src={{profile.profile_img.url}} class="bg-gray-200 rounded-full w-10 h-10">
                                        </a>
                                        <div class="flex flex-col">
                                            <span class="block capitalize font-semibold"> {{profile.user.username}} </span>
                                            <span class="block capitalize text-sm"> {{profile.location}} </span>
                                        </div>
                                    </div>
                                    
                                



                                </div>
                                {% endfor %}
                            </div>

                        </div>

                      

                    </div> 

                </div>               
          

            </div>

        </div>

    </div>








 <!-- Scripts
    ================================================== -->
    <script src="{% static 'assets/js/tippy.all.min.js' %}"></script>  
    <script src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'assets/js/uikit.js' %}"></script>
    <script src="{% static 'assets/js/simplebar.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>


    <script src="{% static '../../unpkg.com/ionicons%405.2.3/dist/ionicons.js' %}"></script>
</body>


</html>

templates/profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">


<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="" />
    <meta name="keywords" content="" />
	<title>Profile - {{username}}</title>
   <!-- <link rel="icon" href="images/fav.png" type="image/png" sizes="16x16"> -->
    
    <link rel="stylesheet" href="{% static 'css/main.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/color.css' %}">
    <link rel="stylesheet" href="{% static 'css/responsive.css' %}">

</head>
<body>
<!--<div class="se-pre-con"></div>-->
<div class="theme-layout">
	
	</div>
	
	<section>
			<div class="feature-photo">
				 <figure><img src="{% static 'images/resources/timeline-1.jpg' %}" alt=""></figure>
				
					<div class="add-btn">
					<span style="color: white; font-size: 27px; margin-right: 520px;"><b><u><a href="/">Home</a></u></b></span>
					<span style="color: white; font-size: 27px;"><b>{{profile.user.posts_set.count}} Post</b></span>
					<span style="color: white; font-size: 27px;"><b>{{profile_followers}} followers</b></span>
					<span style="color: white; font-size: 27px;"><b>{{profile_following}} following</b></span> 
					
					{% if hide_follow is True  %}
					
					{% else %}
					<form action="{% url 'follow' profile.id %}" method="post" style="z-index: 1000;">
					{% csrf_token %}
					{% if following_exists %}
					<input type="submit" style="background-color: #ffc0cb; border: #ffc0cb;" value="following">
					
					{% else %}
					<input type="submit" style="background-color: #ffc0cb; border: #ffc0cb;" value="follow">
					{% endif %}
					</form>
					{% endif %}

					
						
						
					
					</div>
				</form>

				<!-- <form class="edit-phto">
					<i class="fa fa-camera-retro"></i>
					<label class="fileContainer">
						Upload Cover Photo
					<input type="file"/>
					</label>
				</form> -->
				<div class="container-fluid">
					<div class="row merged">
						<div class="col-lg-2 col-sm-3">
							<div class="user-avatar">
								<figure>
									<img src="{{profile.profile_img.url}}" style="height: 250px; width: 100%;object-fit:cover" alt="">
									<form class="edit-phto">
										<i class="fa fa-camera-retro"></i>
										<label class="fileContainer">
											<a href="#account-settings">Upload Profile Photo</a>
										</label>
									</form>
								</figure>
							</div>
						</div>
						<div class="col-lg-10 col-sm-9">
							<div class="timeline-info">
								<ul>
									<li class="admin-name">
									  <h5 style="color: black;white-space: nowrap; width: 110px; font-size: 27px;"><b>@{{profile.user.username}}</b><!--<i class="fa fa-check-circle" style="color: #48dbfb;" aria-hidden="true"></i>--></h5>
									  <!--<span>Group Admin</span>-->
									</li>
									<!--<li>
										<a class="" href="javascript:void(0)" title="" data-ripple="">Go live!</a>
										<a class="" href="javascript:void(0)" title="" data-ripple="">Music</a>
										<a class="" href="emporium/index-3.html" title="" data-ripple="">Emporium</a>
										<a class="" href="fitness/index.html" title="" data-ripple="">Health Inspection</a>
										<a class="" href="settings/account-setting.html" title="" data-ripple="">Settings</a>
										<a class="" href="javascript:void(0)" title="" data-ripple="">Upload</a>
										<a class="" href="time-line.html" title="" data-ripple="">time line</a>
										<a class="" href="timeline-photos.html" title="" data-ripple="">Photos</a>
										<a class="" href="timeline-videos.html" title="" data-ripple="">Videos</a>
										<a class="" href="timeline-friends.html" title="" data-ripple="">Friends</a>
										<a class="" href="timeline-groups.html" title="" data-ripple="">Groups</a>
										<a class="" href="about.html" title="" data-ripple="">about</a>
										<a class="" href="#" title="" data-ripple="">more</a>

									</li>-->
								</ul>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section><!-- top area -->
		<section>
			<div class="bio">
				{{profile.bio}}
			</div>
		</section>
		
	<section>
		<div class="gap gray-bg">
			<div class="container-fluid">
				<div class="row">
					<div class="col-lg-12">
						<div class="row" id="page-contents">
							<div class="col-lg-3">
								<aside class="sidebar static">
									
									
									
								</aside>
							</div><!-- sidebar -->
							









							<div class="col-lg-6">
								<div class="central-meta">
									<ul class="photos">
					{% for post in posts %}
										<li>
											<a class="strip" href="{{post.img.url}}" title="" data-strip-group="mygroup" data-strip-group-options="loop: false"> 
												<img src="{{post.img.url}}" style="height: 250px; width: 300px;object-fit:cover" alt=""></a>
										</li>
										{% endfor %}
									</ul>
									<!--<div class="lodmore"><button class="btn-view btn-load-more"></button></div>-->
								</div><!-- photos -->
							</div><!-- centerl meta -->
							<div class="col-lg-3">
								<aside class="sidebar static">
									
								</aside>
							</div><!-- sidebar -->
						</div>	
					</div>
				</div>
			</div>
		</div>	
	</section>

	
	
	<script data-cfasync="false" src="{% static '../../cdn-cgi/scripts/5c5dd728/cloudflare-static/email-decode.min.js' %}"></script><script src="js/main.min.js"></script>
	<script src="{% static 'js/script.js' %}"></script>

</body>	


</html>

templates/setting.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'assets/images/favicon.png' %}" rel="icon" type="image/png">
    <title>Settings</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'assets/css/icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/uikit.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/tailwind.css' %}">

</head>

<body>


       

          

            <div class="container m-auto"> 

                <h1 class="text-2xl leading-none text-gray-900 tracking-tight mt-3"> Account Setting </h1>
<hr style="margin-top:10px">

<form action="" method="post" enctype="multipart/form-data">
                <div class="grid lg:grid-cols-3 mt-12 gap-8">
                    <div>
                        <h3 class="text-xl mb-2"> Basic</h3>
                        <p></p>
                    </div>
                        {% csrf_token %}
                        <div class="bg-white rounded-md lg:shadow-lg shadow col-span-2">
                            <div>
                                
                                <div class="grid lg:p-6 pt-4">
                                    
                                
                                <div>
                                    <label for=""> Profile Picture</label>
                                    <img src={{profile.profile_img.url}} style="margin-bottom:10px">
                                    <input type="file" class="shadow-none bg-gray-100" name="profileImg" default:"">
                            </div>
                                </div>
                                <div class="grid grid-cols-2 gap-3 lg:p-6 p-4">
                               <div class="col-span-2">
                                   <label for=""> Email</label>
                                   <input type="text" placeholder="Your name.." class="shadow-none bg-gray-100" value="{{profile.user.email}}" readonly> 
                               </div>
                               <div>
                                   <label for=""> First name</label>
                                   <input type="text" name="first_name" placeholder="Your name.." class="shadow-none bg-gray-100" value="{{profile.user.first_name}}">
                               </div>
                               <div>
                                   <label for=""> Last name</label>
                                   <input type="text" name="last_name" placeholder="Your name.." class="shadow-none bg-gray-100" value="{{profile.user.last_name}}">
                                </div>
                                <div class="col-span-2">
                                    <label for="about">Bio</label>
                                    <textarea id="about" name="bio" rows="3"  class="shadow-none bg-gray-100" style="padding:10px">{{profile.bio}}</textarea>
                                </div>
                                <div class="col-span-2">
                                    <label for=""> Location</label>
                                    <input type="text" name="location" placeholder="" class="shadow-none bg-gray-100" value="{{profile.location}}">
                                </div>
                        
                           </div>
                    
    
                       <div class="bg-gray-10 p-6 pt-0 flex justify-end space-x-3">
                           <a href="{% url "index" %}" class="p-2 px-4 rounded bg-gray-50 text-red-500"> Cancel </a>
                           <button type="submit" class="button bg-blue-700"> Save </button>
                       </div>
                    </form>
                    </div>

                    
    
                    </div>
                    <br>

                </div>

            </div>
            
        </div>

    </div>


    

 <!-- Scripts
    ================================================== -->
    <script src="{% static 'assets/js/tippy.all.min.js' %}"></script>  
    <script src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'assets/js/uikit.js' %}"></script>
    <script src="{% static 'assets/js/simplebar.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>


    <script src="{% static '../../unpkg.com/ionicons%405.2.3/dist/ionicons.js' %}"></script>



</body>

</html>

templates/signin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">



<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="{% static 'assets/images/favicon.png' %}" rel="icon" type="image/png">
    <title>sign in</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'assets/css/icons.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/uikit.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'assets/css/tailwind.css' %}">

</head>

<body class="bg-gray-100">


    <div id="wrapper" class="flex flex-col justify-between h-screen">

        <!-- header-->
        <div class="bg-white py-4 shadow dark:bg-gray-800">
            <div class="max-w-6xl mx-auto">


                <div class="flex items-center lg:justify-between justify-around">


                       <b><h1 style="font-size: 1.5rem;">InstaClone</h1></b>
                   

                    <div class="capitalize flex font-semibold hidden lg:block my-2 space-x-3 text-center text-sm">
                        
                        <a href={% url "signup" %} class="bg-pink-500 pink-500 px-6 py-3 rounded-md shadow text-white">Register</a>
                    </div>

                </div>
            </div>
        </div>

        <!-- Content-->
        <div>
            <div class="lg:p-12 max-w-md max-w-xl lg:my-0 my-12 mx-auto p-6 space-y-">
                <h1 class="lg:text-3xl text-xl font-semibold  mb-6"> Log in</h1>
                {% if messages %}
                
                {% for message in messages %}
                <p style="color:red">Bad Credentials</p>
                {% endfor %}
                
                {% endif %}
                <form action="" method="POST">
                    {% csrf_token %}
                    <input type="text" name="username" placeholder="Username" class="bg-gray-200 mb-2 shadow-none dark:bg-gray-800" style="border: 1px solid #d3d5d8 !important;">
                    <input type="text" name="password" placeholder="***********" class="bg-gray-200 mb-2 shadow-none dark:bg-gray-800" style="border: 1px solid #d3d5d8 !important;">
                    
                    <button type="submit" class="bg-gradient-to-br from-pink-500 py-3 rounded-md text-white text-xl to-red-400 w-full">Login</button>
                    <div class="text-center mt-5 space-x-2">
                        <p class="text-base"> Not registered? <a href={% url "signup" %} class=""> Create a account </a></p>
                    </div>
                </form>
            </div>
        </div>
        
        <!-- Footer -->

        <div class="lg:mb-5 py-3 uk-link-reset">
            <div class="flex flex-col items-center justify-between lg:flex-row max-w-6xl mx-auto lg:space-y-0 space-y-3">
                <div class="flex space-x-2 text-gray-700 uppercase">
                    <a href="#"> About</a>
                    <a href="#"> Help</a>
                    <a href="#"> Terms</a>
                    <a href="#"> Privacy</a>
                </div>
                <p class="capitalize"> © copyright 2020 by socol</p>
            </div>
        </div>

    </div>


    <!--<script>
        
        (function (window, document, undefined) {
            'use strict';
            if (!('localStorage' in window)) return;
            var nightMode = localStorage.getItem('gmtNightMode');
            if (nightMode) {
                document.documentElement.className += ' dark';
            }
        })(window, document);
    
    
        (function (window, document, undefined) {
    
            'use strict';
    
            // Feature test
            if (!('localStorage' in window)) return;
    
            // Get our newly insert toggle
            var nightMode = document.querySelector('#night-mode');
            if (!nightMode) return;
    
            // When clicked, toggle night mode on or off
            nightMode.addEventListener('click', function (event) {
                event.preventDefault();
                document.documentElement.classList.toggle('dark');
                if (document.documentElement.classList.contains('dark')) {
                    localStorage.setItem('gmtNightMode', true);
                    return;
                }
                localStorage.removeItem('gmtNightMode');
            }, false);
    
        })(window, document);
    </script>-->

    <!-- Scripts
    ================================================== -->
    <script src="{% static 'assets/js/tippy.all.min.js' %}"></script>
    <script src="{% static 'assets/js/jquery-3.3.1.min.js' %}"></script>
    <script src="{% static 'assets/js/uikit.js' %}"></script>
    <script src="{% static 'assets/js/simplebar.js' %}"></script>
    <script src="{% static 'assets/js/custom.js' %}"></script>


</body>


</html>